use_frameworks!

platform :ios, '8.0'

install! 'cocoapods',
        :generate_multiple_pod_projects => true,
        :incremental_installation => true

target 'HDCollectionView_Example' do
  pod 'HDCollectionView', :path => '../'

  pod 'MJRefresh'
  pod 'SDAutoLayout', '~> 2.1.3'
  pod 'Masonry'
  pod 'SDWebImage', '~> 4.0'
  pod 'SJAttributesFactory'
  pod 'YYModel', '~> 1.0.4'
  pod 'JXCategoryView', '~> 1.3.3'
  
  target 'HDCollectionView_Tests' do
    inherit! :search_paths

    
  end
end
